#!/bin/bash
#
# Usage: start_local_bg_fserver [<port>]
#

# find the directory this script is being run from
DIR=$(dirname $(realpath "${BASH_SOURCE[0]}"))

echo "Switching fserver to use base directory:"
echo "   $DIR/fserver-data"

# if DIR has '&' in it somewhere, this won't work
perl -p -i -e "s&^base_dir = .*&base_dir = \"$DIR/fserver-data\"&" fserver.py

echo "Starting fserver"
echo "Test web server is logging to /tmp/fserver-test-server.log"
cd $DIR
unset http_proxy
unset ftp_proxy
python test-server.py $1 >>/tmp/fserver-test-server.log 2>&1 &!

